services:
  server:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx.dockerfile
    container_name: server-nginx
    volumes:
      - ./app:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - '800:80'
    depends_on:
      - php
      - database
  database:
    image: mariadb:10.6.20
    container_name: database-mariadb
    volumes:
      - dbstore:/var/lib/mysql
    env_file:
      - ./env/mariadb.env
    ports:
      - "3307:3306"
  php:
    build:
      context: .
      args:
        - IMAGE_VERSION=8.1-debian-12
      dockerfile: ./dockerfiles/php-fpm.dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/var/www/app:delegated
      - ./php-fpm/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
  #utils containers
  composer:
    build:
     context: .
     dockerfile: ./dockerfiles/composer.dockerfile
    container_name: composer
    volumes:
      - ./app:/var/www/app
  symfonycli:
    build:
      context: .
      dockerfile: ./dockerfiles/symfony.dockerfile
      args:
        - GIT_EMAIL="rossto3v@gmail.com"
        - GIT_USERNAME="Rosen Stoev"
    container_name: symfonycli
    volumes:
      - ./app:/var/www/app
  commander:
    build:
      context: .
      dockerfile: ./dockerfiles/php-fpm.dockerfile
    container_name: commander
    volumes:
      - ./app:/var/www/app
    entrypoint: ["php", "/var/www/app/bin/console"]
  npm:
    image: node:latest
    container_name: npm
    working_dir: /var/www/app
    entrypoint: ["npm"]
    volumes:
      - ./app:/var/www/app
  yarn:
    image: node:latest
    container_name: yarn
    working_dir: /var/www/app
    entrypoint: ["yarn"]
    volumes:
      - ./app:/var/www/app

volumes:
  dbstore: